cluster:
  children:
    master:
      hosts:
        k3s_master:
          ansible_ssh_user: ubuntu
          ansible_host: 10.8.0.1
          ansible_ssh_port: 22
          ansible_ssh_private_key_file: "~/.ssh/id_rsa"
          ansible_host_key_checking: false
    node:
      hosts:
        k3s_node_1:
          ansible_ssh_user: ubuntu
          ansible_host: 10.8.0.2
          ansible_ssh_port: 22
          ansible_ssh_private_key_file: "~/.ssh/id_rsa"
          ansible_host_key_checking: false
        k3s_node_2:
          become: true
          ansible_host: 10.8.0.3
          ansible_connection: local
          ansible_host_key_checking: false
          ansible_python_interpreter: "{{ansible_playbook_python}}"
