- name: Fetch master node IP
  set_fact:
    k3s_master_ip: "{{ hostvars[inventory_hostname]['ansible_host'] }}"

- name: Download and install k3s
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="v1.32.3+k3s1" K3S_KUBECONFIG_MODE=644 INSTALL_K3S_EXEC="server --node-ip  {{ k3s_master_ip }}  --node-external-ip  {{ k3s_master_ip }} --flannel-iface wg0" sh -
  args:
    executable: /bin/bash
  register: install_k3s
  changed_when: "'Installing k3s' in install_k3s.stdout"
  become: true

- name: Check k3s version and cluster info
  shell: |
    k3s --version
    k3s kubectl cluster-info
    k3s kubectl get nodes
    k3s kubectl get endpoints -A
  register: k3s_info
  changed_when: false
  become: true

- name: Display k3s information
  debug:
    var: k3s_info.stdout_lines

- name: Get K3s Master Token as a fact
  shell: cat /var/lib/rancher/k3s/server/node-token
  register: k3s_master_token_std
  changed_when: false
  become: true

- name: Set K3s Master Token as a fact
  set_fact:
    k3s_master_token: "{{ k3s_master_token_std.stdout }}"

- name: Get K3s Master cluster conf
  slurp:
    src: /etc/rancher/k3s/k3s.yaml
  register: k3s_master_conf_std
  changed_when: false
  become: true

# - name: Set K3s Master Token as a fact
#   set_fact:
#     k3s_master_conf: "{{ k3s_master_conf_std.content  }}"

# - name: Display K3s Master Conf
#   debug:
#     var: k3s_master_conf