- name: Uninstall WireGuard
  apt:
    name: wireguard
    state: absent
    purge: yes
    force: true
  become: true

- name: Uninstall Tools
  apt:
    name: wireguard-tools
    state: absent
    purge: yes
    force: true
  become: true

- name: Cleaning the root paths
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/wireguard"
    - "/etc/systemd/system/wg-quick@wg0"
    - "/usr/lib/systemd/system/wg-quick@wg0"
    - "/usr/lib/systemd/system/wg-quick.target"
    - "/usr/lib/systemd/system/wg-quick@.service"
  become: true

- name: Reload Systemd
  systemd:
    daemon_reload: yes
  become: true

- name: Reset failed systemd units
  command: systemctl reset-failed
  become: true
  changed_when: false
  