cluster:
  children:
    master:
      hosts:
        vpn_master:
          ansible_ssh_user: ubuntu
          ansible_host: 999.999.46.999
          ansible_ssh_port: 22
          ansible_ssh_private_key_file: "~/.ssh/id_rsa"
          ansible_host_key_checking: false
    node:
      hosts:
        vpn_node_1:
          ansible_ssh_user: ubuntu
          ansible_host: 999.999.10.231
          ansible_ssh_port: 22
          ansible_ssh_private_key_file: "~/.ssh/id_rsa"
          ansible_host_key_checking: false
        vpn_node_aws:
          ansible_ssh_user: ubuntu
          ansible_host: 3.999.999.174
          ansible_ssh_port: 22
          ansible_ssh_private_key_file: "~/.ssh/key.pem"
          ansible_host_key_checking: false
        vpn_node_2:
          become: true
          ansible_host: 127.0.0.1
          ansible_connection: local
          ansible_host_key_checking: false
          ansible_python_interpreter: "{{ansible_playbook_python}}"
