- name: Fetch master node IP
  set_fact:
    k3s_node_ip: "{{ hostvars[inventory_hostname]['ansible_host'] }}"

- name: Fetch master IP
  set_fact:
    k3s_master_ip: "{{ hostvars['k3s_master'].k3s_master_ip }}"

- name: K3s Master ip
  debug:
    var: k3s_master_ip

- name: Fetch master token
  set_fact:
    k3s_master_token: "{{ hostvars['k3s_master'].k3s_master_token }}"

- name: Download and install k3s
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="v1.28.3+k3s2" K3S_KUBECONFIG_MODE=644 INSTALL_K3S_EXEC="agent --server https://{{ k3s_master_ip }}:6443 --token {{ k3s_master_token }} --node-ip {{ k3s_node_ip }} --node-external-ip {{ k3s_node_ip }} --flannel-iface wg0"  sh -
  args:
    executable: /bin/bash
  register: install_k3s
  changed_when: "'Installing k3s' in install_k3s.stdout"
  become: true

- name: Ensure the destination directory exists
  file:
    path: ~/.kube
    state: directory

- name: Save conf cluster file to the node
  copy:
    content: "{{ hostvars['k3s_master'].k3s_master_conf_std.content | b64decode}}"
    dest: ~/.kube/config
   
- name: Update server address in kubeconfig
  ansible.builtin.replace:
    path: ~/.kube/config
    regexp: 'https://127.0.0.1:6443'
    replace: 'https://10.8.0.1:6443'
    backup: yes

- name: Check k3s version and cluster info
  shell: |
    k3s --version
    k3s kubectl cluster-info
    k3s kubectl get nodes
    k3s kubectl get endpoints -A
  register: k3s_info
  changed_when: false

- name: Display k3s information
  debug:
    var: k3s_info.stdout_lines
