- name: Wait for the VM to respond to ping
  ping:
  register: ping_result
  until: ping_result is success
  retries: 3
  delay: 60

- name: Update system task
  become: true
  apt:
    update_cache: yes
    upgrade: full
    autoclean: yes
    autoremove: yes



