- name: Uncomment net.ipv4.ip_forward in /etc/sysctl.conf
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    regexp: '^#(net.ipv4.ip_forward\s*=\s*1)'
    line: 'net.ipv4.ip_forward = 1'
    backrefs: yes
  become: true

- name: Uncomment net.ipv6.conf.all.forwarding in /etc/sysctl.conf
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    regexp: '^#(net.ipv6.conf.all.forwarding\s*=\s*1)'
    line: 'net.ipv6.conf.all.forwarding = 1'
    backrefs: yes
  become: true

- name: Enable IP forwarding
  become: true
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes

- name: Creating wireguard config dir
  file:
    path: "/etc/wireguard"
    state: directory
  register: wg_conf_dir
  become: true

- name: Checking WireGuard private key
  ansible.builtin.stat:
    path: "{{ wg_conf_dir.path }}/privatekey"
  register: wg_private_key
  become: true

- name: Generating wireguard private and public keys [skip if exits]
  become: true
  shell: |
      umask 077 && wg genkey | tee {{ wg_conf_dir.path }}/privatekey | wg pubkey > {{ wg_conf_dir.path }}/publickey
  when: not wg_private_key.stat.exists

- name: Checking keys status
  debug:
    msg: "keys exit!"
  when: wg_private_key.stat.exists